"""add balance and interactions tables

Revision ID: 6fb5cb200f37
Revises: fb59de640476
Create Date: 2026-02-06 08:59:35.592200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6fb5cb200f37'
down_revision: Union[str, Sequence[str], None] = 'fb59de640476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Creamos las tablas nuevas (Esto no da error)
    op.create_table('cartitem',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    op.create_table('purchase',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('purchase_date', sa.DateTime(), nullable=False),
        sa.Column('price_at_purchase', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 2. Borramos la tabla de prueba si existe
    op.drop_table('playing_with_neon')

    # 3. EL TRUCO PARA EL BALANCE:
    # Primero la creamos permitiendo NULL
    op.add_column('user', sa.Column('balance', sa.Float(), nullable=True))
    
    # Llenamos los valores existentes con 0.0
    op.execute('UPDATE "user" SET balance = 0.0 WHERE balance IS NULL')
    
    # Ahora que todos tienen 0.0, la hacemos NOT NULL
    op.alter_column('user', 'balance', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'balance')
    op.drop_constraint('unique_user_product_like', 'productlike', type_='unique')
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.drop_table('purchase')
    op.drop_table('cartitem')
    # ### end Alembic commands ###
