"""remove_old_affiliate_field

Revision ID: b45293c9d002
Revises: eeac6ab839e0
Create Date: 2026-02-02 09:27:14.484427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b45293c9d002'
down_revision: Union[str, Sequence[str], None] = 'eeac6ab839e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'affiliate_link')
    #op.create_unique_constraint('unique_user_product_like', 'productlike', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('unique_user_product_like', 'productlike', type_='unique')
    op.add_column('product', sa.Column('affiliate_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
