"""add reputation to user

Revision ID: fb59de640476
Revises: b45293c9d002
Create Date: 2026-02-04 08:13:00.347414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb59de640476'
down_revision: Union[str, Sequence[str], None] = 'b45293c9d002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('user', sa.Column('reputation', sa.Integer(), nullable=True))
    
    op.execute("UPDATE \"user\" SET reputation = 0")
    
    op.alter_column('user', 'reputation', nullable=False)
    



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reputation')
